import { images64 } from "./images64"

export const characters = [

    {
        name: (Math.random() < 1/4 ? "Cesar" : Math.random() < 1/3 ? "Pablo" : Math.random() ? "Steve" : "Jaime"),
        image: images64.Bill,
        head: "glasses",
        hair: "gray",
        skin: "light",
        gender: "male",
        clothing: ["jacket", "tie", "pants"],
        shirt: "blue",
        pants: "gray",
        shoes: ["blue", "white"],
        accessories: "science stuff",
        id: 1,
    },

    {
        name: (Math.random() < 1/3 ? "Codee" : Math.random() < 0.5 ? "Kyle" : "Senyon"),
        image: images64.Brodie,
        head: "hat",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: ["jacket", "pants"],
        shirt: "red",
        pants: "gray",
        shoes: "gray",
        accessories: ["whistle", "basketball"],
        id: 2,
    },

    {
        name: (Math.random() < 0.5 ? "Skye" : "Audra"),
        image: images64.Chloe,
        head: "none",
        hair: "blonde",
        skin: "light",
        gender: "female",
        clothing: ["jacket", "skirt"],
        shirt: "purple",
        pants: "none",
        shoes: "black",
        accessories: "writing pad",
        id: 3,
    },

    {
        name: (Math.random() < 0.5 ? "Yaya" : "Jodee"),
        image: images64.Elaine,
        head: "glasses",
        hair: "gray",
        skin: "dark",
        gender: "female",
        clothing: "skirt",
        shirt: "pink",
        pants: "none",
        shoes: "red",
        accessories: "books",
        id: 4,
    },

    {
        name: "Kendall",
        image: images64.Emily,
        head: "none",
        hair: "blonde",
        skin: "light",
        gender: "female",
        clothing: "pants",
        shirt: "blue",
        pants: "blue",
        shoes: ["gray", "white"],
        accessories: "animals",
        id: 5,
    },

    {
        name: (Math.random() < 0.5 ? "Patience" : "Katie"),
        image: images64.Erika,
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "female",
        clothing: "skirt",
        shirt: "purple",
        pants: "none",
        shoes: "black",
        accessories: ["purse", "badge"],
        id: 6,
    },

    {
        name: "Hope",
        image: images64.Jada,
        head: "none",
        hair: "brown",
        skin: "dark",
        gender: "female",
        clothing: ["jacket", "pants"],
        shirt: "green",
        pants: "blue",
        shoes: "brown",
        accessories: "badge",
        id: 7,
    },

    {
        name: (Math.random() < 1/3 ? "Andrew" : Math.random() < 0.5 ? "Lester" : "Cooper"),
        image: images64.Jakob,
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "male",
        clothing: ["tie", "pants"],
        shirt: "pink",
        pants: "blue",
        shoes: "black",
        accessories: "math stuff",
        id: 8,
    },

    {
        name: (Math.random() < 0.5 ? "Charly" : "Sophia"),
        image: images64.Jazzy,
        head: "none",
        hair: "black",
        skin: "dark",
        gender: "female",
        clothing: "pants",
        shirt: "purple",
        pants: "black",
        shoes: "black",
        accessories: "microphone",
        id: 9,
    },

    {
        name: "Zasha",
        image: images64.Jerry,
        head: "glasses",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: ["tie", "pants"],
        shirt: "purple",
        pants: "blue",
        shoes: "brown",
        accessories: "none",
        id: 10,
    },

    {
        name: (Math.random() < 0.5 ? "Mina" : "Athena"),
        image: images64.Jessica,
        head: "none",
        hair: "brown",
        skin: "dark",
        gender: "female",
        clothing: "pants",
        shirt: "blue",
        pants: "blue",
        shoes: "gray",
        accessories: "whistle",
        id: 11,
    },

    {
        name: "Vanessa",
        image: images64.Korbyn,
        head: "none",
        hair: "orange",
        skin: "light",
        gender: "female",
        clothing: "pants",
        shirt: "pink",
        pants: "blue",
        shoes: "brown",
        accessories: ["purse", "badge"],
        id: 12,
    },

    {
        name: "Lauren",
        image: images64.Lauren,
        head: "hat",
        hair: "brown",
        skin: "dark",
        gender: "female",
        clothing: "pants",
        shirt: "blue",
        pants: "blue",
        shoes: "gray",
        accessories: "clipboard",
        id: 13,
    },

    {
        name: (Math.random() < 1/3 ? "Rony" : Math.random() < 0.5 ? "Gavin" : "Sam"),
        image: images64.Lyle,
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "male",
        clothing: ["apron", "pants"],
        shirt: "blue",
        pants: "brown",
        shoes: "brown",
        accessories: "none",
        id: 14,
    },

    {
        name: (Math.random() < 0.5 ? "Bri" : "Madelyn"),
        image: images64.Mia,
        head: "bow/headband",
        hair: "black",
        skin: "light",
        gender: "female",
        clothing: ["apron", "pants"],
        shirt: "pink",
        pants: "red",
        shoes: "",
        accessories: "",
        id: 15,
    },

    {
        name: (Math.random() < 0.5 ? "Michelle" : "Madi"),
        image: images64.Michelle,
        head: "glasses",
        hair: "gray",
        skin: "light",
        gender: "female",
        clothing: ["jacket", "pants"],
        shirt: "red",
        pants: "gray",
        shoes: "black",
        accessories: "none",
        id: 16,
    },

    {
        name: (Math.random() < 0.5 ? "Brandon" : "Angel"),
        image: images64.Mike,
        head: "hat",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: "pants",
        shirt: "blue",
        pants: "black",
        shoes: "black",
        accessories: "badge",
        id: 17,
    },

    {
        name: "Elayna",
        image: images64.Roberta,
        head: "glasses",
        hair: "brown",
        skin: "light",
        gender: "female",
        clothing: "skirt",
        shirt: "purple",
        pants: "none",
        shoes: "purple",
        accessories: "none",
        id: 18,
    },

    {
        name: (Math.random() < 0.5 ? "Carla" : "Thia"),
        image: images64.Rosie,
        head: "hat",
        hair: "gray",
        skin: "dark",
        gender: "female",
        clothing: ["apron", "pants"],
        shirt: "green",
        pants: "gray",
        shoes: "black",
        accessories: "none",
        id: 19,
    },

    {
        name: (Math.random() < 0.5 ? "Nadya" :"Meg"),
        image: images64.Scottie,
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "female",
        clothing: "skirt",
        shirt: "pink",
        pants: "none",
        shoes: "blue",
        accessories: "books",
        id: 20,
    },

    {
        name: (Math.random() < 0.5 ? "Mackenzie" : "Julia"),
        image: images64.Susan,
        head: ["glasses", "bow/headband"],
        hair: "orange",
        skin: "light",
        gender: "female",
        clothing: ["skirt", "pants"],
        shirt: "green",
        pants: "green",
        shoes: "red",
        accessories: "mask",
        id: 21,
    },

    {
        name: (Math.random() < 1/3 ? "R J" : Math.random() < 0.5 ? "Justin" : "Nate"),
        image: images64.Derrick,
        head: "none",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: ["tie", "pants"],
        shirt: "white",
        pants: "gray",
        shoes: "black",
        accessories: "computer",
        id: 22,
    },

    {
        name: (Math.random() < 0.5 ? "Kat" : "Gareth"),
        image: images64.Terry,
        head: "hat",
        hair: "brown",
        skin: "light",
        gender: "male",
        clothing: "pants",
        shirt: "blue",
        pants: "brown",
        shoes: "brown",
        accessories: "broom",
        id: 23,
    },

    {
        name: (Math.random() < 1/3 ? "Mark" : Math.random() < 0.5 ? "Dale" : "D'Angelo"),
        image: images64.Warren,
        head: "none",
        hair: "gray",
        skin: "light",
        gender: "male",
        clothing: ["jacket", "tie", "pants"],
        shirt: "white",
        pants: "gray",
        shoes: "black",
        accessories: "none",
        id: 24,
    }

]
