export const characters = [

    {
        name: "Bill",
        image: "/images/characters/Bill.png",
        head: "glasses",
        hair: "gray",
        skin: "light",
        gender: "male",
        clothing: ["jacket", "tie", "pants"],
        shirt: "blue",
        pants: "gray",
        shoes: ["blue", "white"],
        accessories: "science stuff",
        id: 1,
    },

    {
        name: "Brodie",
        image: "/images/characters/Brodie.png",
        head: "hat",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: ["jacket", "pants"],
        shirt: "red",
        pants: "gray",
        shoes: "gray",
        accessories: ["whistle", "basketball"],
        id: 2,
    },

    {
        name: "Chloe",
        image: "/images/characters/Chloe.png",
        head: "none",
        hair: "blonde",
        skin: "light",
        gender: "female",
        clothing: ["jacket", "skirt"],
        shirt: "purple",
        pants: "none",
        shoes: "black",
        accessories: "writing pad",
        id: 3,
    },

    {
        name: "Elaine",
        image: "/images/characters/Elaine.png",
        head: "glasses",
        hair: "gray",
        skin: "dark",
        gender: "female",
        clothing: "skirt",
        shirt: "pink",
        pants: "none",
        shoes: "red",
        accessories: "books",
        id: 4,
    },

    {
        name: "Emily",
        image: "/images/characters/Emily.png",
        head: "none",
        hair: "blonde",
        skin: "light",
        gender: "female",
        clothing: "pants",
        shirt: "blue",
        pants: "blue",
        shoes: ["gray", "white"],
        accessories: "animals",
        id: 5,
    },

    {
        name: "Erika",
        image: "/images/characters/Erika.png",
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "female",
        clothing: "skirt",
        shirt: "purple",
        pants: "none",
        shoes: "black",
        accessories: ["purse", "badge"],
        id: 6,
    },

    {
        name: "Jada",
        image: "/images/characters/Jada.png",
        head: "none",
        hair: "brown",
        skin: "dark",
        gender: "female",
        clothing: ["jacket", "pants"],
        shirt: "green",
        pants: "blue",
        shoes: "brown",
        accessories: "badge",
        id: 7,
    },

    {
        name: "Jakob",
        image: "/images/characters/Jakob.png",
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "male",
        clothing: ["tie", "pants"],
        shirt: "pink",
        pants: "blue",
        shoes: "black",
        accessories: "math stuff",
        id: 8,
    },

    {
        name: "Jazzy",
        image: "/images/characters/Jazzy.png",
        head: "none",
        hair: "black",
        skin: "dark",
        gender: "female",
        clothing: "pants",
        shirt: "purple",
        pants: "black",
        shoes: "black",
        accessories: "microphone",
        id: 9,
    },

    {
        name: "Jerry",
        image: "/images/characters/Jerry.png",
        head: "glasses",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: ["tie", "pants"],
        shirt: "purple",
        pants: "blue",
        shoes: "brown",
        accessories: "none",
        id: 10,
    },

    {
        name: "Jessica",
        image: "/images/characters/Jessica.png",
        head: "none",
        hair: "brown",
        skin: "dark",
        gender: "female",
        clothing: "pants",
        shirt: "blue",
        pants: "blue",
        shoes: "gray",
        accessories: "whistle",
        id: 11,
    },

    {
        name: "Korbyn",
        image: "/images/characters/Korbyn.png",
        head: "none",
        hair: "orange",
        skin: "light",
        gender: "female",
        clothing: "pants",
        shirt: "pink",
        pants: "blue",
        shoes: "brown",
        accessories: ["purse", "badge"],
        id: 12,
    },

    {
        name: "Lauren",
        image: "/images/characters/Lauren.png",
        head: "hat",
        hair: "brown",
        skin: "dark",
        gender: "female",
        clothing: "pants",
        shirt: "blue",
        pants: "blue",
        shoes: "gray",
        accessories: "clipboard",
        id: 13,
    },

    {
        name: "Lyle",
        image: "/images/characters/Lyle.png",
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "male",
        clothing: ["apron", "pants"],
        shirt: "blue",
        pants: "brown",
        shoes: "brown",
        accessories: "none",
        id: 14,
    },

    {
        name: "Mia",
        image: "/images/characters/Mia.png",
        head: "bow/headband",
        hair: "black",
        skin: "light",
        gender: "female",
        clothing: ["apron", "pants"],
        shirt: "pink",
        pants: "red",
        shoes: "",
        accessories: "",
        id: 15,
    },

    {
        name: "Michelle",
        image: "/images/characters/Michelle.png",
        head: "glasses",
        hair: "gray",
        skin: "light",
        gender: "female",
        clothing: ["jacket", "pants"],
        shirt: "red",
        pants: "gray",
        shoes: "black",
        accessories: "none",
        id: 16,
    },

    {
        name: "Mike",
        image: "/images/characters/Mike.png",
        head: "hat",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: "pants",
        shirt: "blue",
        pants: "black",
        shoes: "black",
        accessories: "badge",
        id: 17,
    },

    {
        name: "Roberta",
        image: "/images/characters/Roberta.png",
        head: "glasses",
        hair: "brown",
        skin: "light",
        gender: "female",
        clothing: "skirt",
        shirt: "purple",
        pants: "none",
        shoes: "purple",
        accessories: "none",
        id: 18,
    },

    {
        name: "Rosie",
        image: "/images/characters/Rosie.png",
        head: "hat",
        hair: "gray",
        skin: "dark",
        gender: "female",
        clothing: ["apron", "pants"],
        shirt: "green",
        pants: "gray",
        shoes: "black",
        accessories: "none",
        id: 19,
    },

    {
        name: "Scottie",
        image: "/images/characters/Scottie.png",
        head: "none",
        hair: "brown",
        skin: "light",
        gender: "female",
        clothing: "skirt",
        shirt: "pink",
        pants: "none",
        shoes: "blue",
        accessories: "books",
        id: 20,
    },

    {
        name: "Susan",
        image: "/images/characters/Susan.png",
        head: ["glasses", "bow/headband"],
        hair: "orange",
        skin: "light",
        gender: "female",
        clothing: ["skirt", "pants"],
        shirt: "green",
        pants: "green",
        shoes: "red",
        accessories: "mask",
        id: 21,
    },

    {
        name: "Derrick",
        image: "/images/characters/Derrick.png",
        head: "none",
        hair: "black",
        skin: "dark",
        gender: "male",
        clothing: ["tie", "pants"],
        shirt: "white",
        pants: "gray",
        shoes: "black",
        accessories: "computer",
        id: 22,
    },

    {
        name: "Terry",
        image: "/images/characters/Terry.png",
        head: "hat",
        hair: "brown",
        skin: "light",
        gender: "male",
        clothing: "pants",
        shirt: "blue",
        pants: "brown",
        shoes: "brown",
        accessories: "broom",
        id: 23,
    },

    {
        name: "Warren",
        image: "/images/characters/Warren.png",
        head: "none",
        hair: "gray",
        skin: "light",
        gender: "male",
        clothing: ["jacket", "tie", "pants"],
        shirt: "white",
        pants: "gray",
        shoes: "black",
        accessories: "none",
        id: 24,
    }

]