import { images64 } from "./images64";

function randomFrom(array) {
  return array[Math.floor(Math.random() * array.length)];
}

const baseCharacters = [
  {
    names: ["Cesar", "Pablo", "Steve", "Jaime"],
    image: images64.Bill,
    head: "glasses",
    hair: "gray",
    skin: "light",
    gender: "male",
    clothes: ["jacket", "tie", "pants"],
    shirt: "blue",
    pants: "gray",
    shoes: ["blue", "white"],
    accessories: "science stuff",
    id: 1,
  },
  {
    names: ["Codee", "Kyle", "Senyon"],
    image: images64.Brodie,
    head: "hat",
    hair: "black",
    skin: "dark",
    gender: "male",
    clothes: ["jacket", "pants"],
    shirt: "red",
    pants: "gray",
    shoes: "gray",
    accessories: ["whistle", "basketball"],
    id: 2,
  },
  {
    names: ["Skye", "Audra"],
    image: images64.Chloe,
    head: "none",
    hair: "blonde",
    skin: "light",
    gender: "female",
    clothes: ["jacket", "skirt"],
    shirt: "purple",
    pants: "none",
    shoes: "black",
    accessories: "writing pad",
    id: 3,
  },
  {
    names: ["Yaya", "Jodee"],
    image: images64.Elaine,
    head: "glasses",
    hair: "gray",
    skin: "dark",
    gender: "female",
    clothes: "skirt",
    shirt: "pink",
    pants: "none",
    shoes: "red",
    accessories: "books",
    id: 4,
  },
  {
    names: ["Kendall", "D.D."],
    image: images64.Emily,
    head: "none",
    hair: "blonde",
    skin: "light",
    gender: "female",
    clothes: "pants",
    shirt: "blue",
    pants: "blue",
    shoes: ["gray", "white"],
    accessories: "animals",
    id: 5,
  },
  {
    names: ["Patience", "Katie"],
    image: images64.Erika,
    head: "none",
    hair: "brown",
    skin: "dark",
    gender: "female",
    clothes: "skirt",
    shirt: "purple",
    pants: "none",
    shoes: "black",
    accessories: ["purse", "badge"],
    id: 6,
  },
  {
    names: ["Hope"],
    image: images64.Jada,
    head: "none",
    hair: ["black", "brown"],
    skin: "dark",
    gender: "female",
    clothes: ["jacket", "pants"],
    shirt: "green",
    pants: "blue",
    shoes: "brown",
    accessories: "badge",
    id: 7,
  },
  {
    names: ["Andrew", "Lester", "Cooper"],
    image: images64.Jakob,
    head: "none",
    hair: "brown",
    skin: "light",
    gender: "male",
    clothes: ["tie", "pants"],
    shirt: "pink",
    pants: "blue",
    shoes: "black",
    accessories: "math stuff",
    id: 8,
  },
  {
    names: ["Charly", "Sophia"],
    image: images64.Jazzy,
    head: "none",
    hair: "black",
    skin: "dark",
    gender: "female",
    clothes: "pants",
    shirt: "purple",
    pants: "black",
    shoes: "black",
    accessories: "none",
    id: 9,
  },
  {
    names: ["Zasha"],
    image: images64.Jerry,
    head: "glasses",
    hair: "black",
    skin: "dark",
    gender: "male",
    clothes: ["tie", "pants"],
    shirt: "purple",
    pants: "blue",
    shoes: "brown",
    accessories: "none",
    id: 10,
  },
  {
    names: ["Mina", "Athena"],
    image: images64.Jessica,
    head: "none",
    hair: "brown",
    skin: "dark",
    gender: "female",
    clothes: "pants",
    shirt: "blue",
    pants: "blue",
    shoes: "gray",
    accessories: "whistle",
    id: 11,
  },
  {
    names: ["Vanessa", "Brittany"],
    image: images64.Korbyn,
    head: "none",
    hair: "orange",
    skin: "light",
    gender: "female",
    clothes: "pants",
    shirt: "pink",
    pants: "blue",
    shoes: "brown",
    accessories: ["purse", "badge"],
    id: 12,
  },
  {
    names: ["Lauren"],
    image: images64.Lauren,
    head: "hat",
    hair: "brown",
    skin: "dark",
    gender: "female",
    clothes: "pants",
    shirt: "blue",
    pants: "blue",
    shoes: "gray",
    accessories: "clipboard",
    id: 13,
  },
  {
    names: ["Rony", "Gavin", "Sam"],
    image: images64.Lyle,
    head: "none",
    hair: "brown",
    skin: "light",
    gender: "male",
    clothes: ["apron", "pants"],
    shirt: "blue",
    pants: "brown",
    shoes: "brown",
    accessories: "none",
    id: 14,
  },
  {
    names: ["Bri", "Madelyn", "Shanice"],
    image: images64.Mia,
    head: "bow/headband",
    hair: "black",
    skin: "dark",
    gender: "female",
    clothes: ["apron", "pants"],
    shirt: "pink",
    pants: "magenta",
    shoes: "purple",
    accessories: "animals",
    id: 15,
  },
  {
    names: ["Michelle", "Madi"],
    image: images64.Michelle,
    head: "glasses",
    hair: "gray",
    skin: "light",
    gender: "female",
    clothes: ["jacket", "pants", "suit"],
    shirt: "red",
    pants: "gray",
    shoes: "black",
    accessories: "none",
    id: 16,
  },
  {
    names: ["Brandon", "Angel"],
    image: images64.Mike,
    head: "hat",
    hair: "black",
    skin: "dark",
    gender: "male",
    clothes: "pants",
    shirt: "blue",
    pants: "black",
    shoes: "black",
    accessories: ["badge", "watch"],
    id: 17,
  },
  {
    names: ["Elayna", "Molly"],
    image: images64.Roberta,
    head: "glasses",
    hair: "brown",
    skin: "light",
    gender: "female",
    clothes: "skirt",
    shirt: "purple",
    pants: "none",
    shoes: "purple",
    accessories: "none",
    id: 18,
  },
  {
    names: ["Carla", "Thia"],
    image: images64.Rosie,
    head: "hat",
    hair: "gray",
    skin: "dark",
    gender: "female",
    clothes: ["apron", "pants"],
    shirt: "green",
    pants: "gray",
    shoes: "black",
    accessories: "none",
    id: 19,
  },
  {
    names: ["Nadya", "Meg"],
    image: images64.Scottie,
    head: "none",
    hair: "brown",
    skin: "light",
    gender: "female",
    clothes: "skirt",
    shirt: "pink",
    pants: "none",
    shoes: "blue",
    accessories: "books",
    id: 20,
  },
  {
    names: ["Mack", "Julia"],
    image: images64.Susan,
    head: ["glasses", "bow/headband"],
    hair: "orange",
    skin: "light",
    gender: "female",
    clothes: ["skirt", "pants"],
    shirt: "green",
    pants: "green",
    shoes: "red",
    accessories: "mask",
    id: 21,
  },
  {
    names: ["RJ", "Justin", "Nate"],
    image: images64.Derrick,
    head: "none",
    hair: "black",
    skin: "dark",
    gender: "male",
    clothes: ["tie", "pants"],
    shirt: "white",
    pants: "gray",
    shoes: "black",
    accessories: "computer",
    id: 22,
  },
  {
    names: ["Kat", "Gareth", "Jesse"],
    image: images64.Terry,
    head: "hat",
    hair: "brown",
    skin: "light",
    gender: "male",
    clothes: "pants",
    shirt: "blue",
    pants: "brown",
    shoes: "brown",
    accessories: "broom",
    id: 23,
  },
  {
    names: ["Mark", "Dale", "D'Angelo"],
    image: images64.Warren,
    head: "none",
    hair: "gray",
    skin: "light",
    gender: "male",
    clothes: ["jacket", "tie", "pants", "suit"],
    shirt: "white",
    pants: "gray",
    shoes: "black",
    accessories: "none",
    id: 24,
  },
];

export function getCharacters() {
  return baseCharacters.map(c => ({
    ...c,
    name: randomFrom(c.names),
  }));
}
